# Generated by Django 3.0.8 on 2020-07-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('ciudad', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=128)),
                ('cp', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('abreviado', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='deporte',
            name='numero_registro',
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('ciudad', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=128)),
                ('cp', models.CharField(max_length=5)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Escuela')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Estado')),
            ],
        ),
        migrations.AddField(
            model_name='escuela',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Estado'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.Escuela')),
                ('sede', models.ManyToManyField(to='deportes.Sede')),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deportes.Categoria'),
        ),
    ]
