# Generated by Django 3.0.8 on 2020-07-08 03:39

from django.db import migrations


def init_values(apps, schema_editor):
    Estado = apps.get_model('deportes', 'Estado')
    Estado.objects.create(nombre='AGUASCALIENTES', abreviado='AGU')
    Estado.objects.create(nombre='BAJA CALIFORNIA', abreviado='BCN')
    Estado.objects.create(nombre='BAJA CALIFORNIA SUR', abreviado='BCS')
    Estado.objects.create(nombre='CAMPECHE', abreviado='CAM')
    Estado.objects.create(nombre='CHIAPAS', abreviado='CHP')
    Estado.objects.create(nombre='CHIHUAHUA', abreviado='CHH')
    Estado.objects.create(nombre='CIUDAD DE MÉXICO', abreviado='CMX3​')
    Estado.objects.create(nombre='COAHUILA', abreviado='COA')
    Estado.objects.create(nombre='COLIMA', abreviado='COL')
    Estado.objects.create(nombre='DURANGO', abreviado='DUR')
    Estado.objects.create(nombre='GUANAJUATO', abreviado='GUA')
    Estado.objects.create(nombre='GUERRERO', abreviado='GRO')
    Estado.objects.create(nombre='HIDALGO', abreviado='HID')
    Estado.objects.create(nombre='JALISCO', abreviado='JAL')
    Estado.objects.create(nombre='MÉXICO', abreviado='MEX')
    Estado.objects.create(nombre='MICHOACÁN', abreviado='MIC')
    Estado.objects.create(nombre='MORELOS', abreviado='MOR')
    Estado.objects.create(nombre='NAYARIT', abreviado='NAY')
    Estado.objects.create(nombre='NUEVO LEÓN', abreviado='NLE')
    Estado.objects.create(nombre='OAXACA', abreviado='OAX')
    Estado.objects.create(nombre='PUEBLA', abreviado='PUE')
    Estado.objects.create(nombre='QUERÉTARO', abreviado='QUE')
    Estado.objects.create(nombre='QUINTANA ROO', abreviado='ROO')
    Estado.objects.create(nombre='SAN LUIS POTOSÍ', abreviado='SLP')
    Estado.objects.create(nombre='SINALOA', abreviado='SIN')
    Estado.objects.create(nombre='SONORA', abreviado='SON')
    Estado.objects.create(nombre='TABASCO', abreviado='TAB')
    Estado.objects.create(nombre='TAMAULIPAS', abreviado='TAM')
    Estado.objects.create(nombre='TLAXCALA', abreviado='TLA')
    Estado.objects.create(nombre='VERACRUZ', abreviado='VER')
    Estado.objects.create(nombre='YUCATÁN', abreviado='YUC')
    Estado.objects.create(nombre='ZACATECAS', abreviado='ZAC')


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_auto_20200707_2232'),
    ]

    operations = [migrations.RunPython(init_values)]
